### ISSUE TITLE
Math / Stats section?

### ISSUE THREAD

**Issue by jrudoler** [openlists/Overview#2]
Love this resource Tom! Perhaps you don't think this would fit, but it could be cool to have a section for more elementary math / stats resources, since things like linalg, probability, statistical inference are important tools for doing good science / cog neuro as well.

Some examples:

Probability course by Joe Blitzstein at Harvard: https://projects.iq.harvard.edu/stat110/youtube

Linear Algebra course by Gilbert String at MIT: https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/video_galleries/video-lectures/

Statistical Inference and Bayesian Data Analysis lectures and code by Richard McElreath at Max Planck Institute: https://github.com/rmcelreath/stat_rethinking_2022

**Comment by TomDonoghue** [comment]
Yeh, I think a math / stats section is a great idea! 

I toyed with the idea of merging with the [DSP](https://github.com/openlists/DSPResources) section, but I think in the end they are fairly distinct. 

I made a new repo for Math & Stats:
https://github.com/openlists/MathStatsResources

@jrudoler - do you want to make a PR there adding any resources you know of? After that I'll also check my notes for any additional resources, and then add it to the Overview / Site, etc.

**Comment by TomDonoghue** [comment]
Closing now this since is now added at https://github.com/openlists/MathStatsResources

Thanks @jrudoler!
